## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import matplotlib.pyplot as plt
import numpy as np
import os
import csv

# Files to load
weather_py_csv = os.path.join("../Weather_Database/WeatherPy_database.csv")



# Import the time library and the datetime module from the datetime library 
import time
from datetime import datetime

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
# Read the school data file and store it in a Pandas DataFrame.
city_data_df = pd.read_csv(weather_py_csv)
city_data_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Bluff,NZ,-46.6000,168.3333,59.70,74,8,2.82,clear sky
1,1,Yellowknife,CA,62.4560,-114.3525,17.42,58,20,3.44,few clouds
2,2,Cidreira,BR,-30.1811,-50.2056,69.26,81,0,8.75,clear sky
3,3,Hambantota,LK,6.1241,81.1185,77.61,87,14,5.75,few clouds
4,4,Cabra,ES,37.4725,-4.4421,55.65,72,98,3.69,overcast clouds
...,...,...,...,...,...,...,...,...,...,...
732,732,Kokoda,PG,-8.8785,147.7407,86.14,68,76,3.53,broken clouds
733,733,San Marcos,US,33.1434,-117.1661,71.71,69,20,10.36,few clouds
734,734,Salalah,OM,17.0151,54.0924,75.29,50,0,4.61,clear sky
735,735,Sechura,PE,-5.5569,-80.8222,77.31,61,98,14.85,overcast clouds
736,736,Arrecife,ES,28.9630,-13.5477,64.38,82,20,8.05,few clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 20
What is the maximum temperature you would like for your trip? 105

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Bluff,NZ,-46.6000,168.3333,59.70,74,8,2.82,clear sky
2,2,Cidreira,BR,-30.1811,-50.2056,69.26,81,0,8.75,clear sky
3,3,Hambantota,LK,6.1241,81.1185,77.61,87,14,5.75,few clouds
4,4,Cabra,ES,37.4725,-4.4421,55.65,72,98,3.69,overcast clouds
6,6,Rikitea,PF,-23.1203,-134.9692,79.18,65,27,8.81,scattered clouds
7,7,Pacific Grove,US,36.6177,-121.9166,64.58,64,86,21.99,overcast clouds
8,8,Westport,US,41.1415,-73.3579,38.89,57,100,13.00,overcast clouds
9,9,Darnah,LY,32.7670,22.6367,58.48,61,87,12.48,overcast clouds
10,10,Mae Sai,TH,20.4335,99.8762,73.69,58,66,2.17,broken clouds
11,11,Hithadhoo,MV,-0.6000,73.0833,81.55,65,5,5.97,clear sky

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                656
City                   656
Country                652
Lat                    656
Lng                    656
Max Temp               656
Humidity               656
Cloudiness             656
Wind Speed             656
Current Description    656
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.
# Drop the NaNs.
preferred_cities_df.dropna()
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Bluff,NZ,-46.6000,168.3333,59.70,74,8,2.82,clear sky
2,2,Cidreira,BR,-30.1811,-50.2056,69.26,81,0,8.75,clear sky
3,3,Hambantota,LK,6.1241,81.1185,77.61,87,14,5.75,few clouds
4,4,Cabra,ES,37.4725,-4.4421,55.65,72,98,3.69,overcast clouds
6,6,Rikitea,PF,-23.1203,-134.9692,79.18,65,27,8.81,scattered clouds
...,...,...,...,...,...,...,...,...,...,...
732,732,Kokoda,PG,-8.8785,147.7407,86.14,68,76,3.53,broken clouds
733,733,San Marcos,US,33.1434,-117.1661,71.71,69,20,10.36,few clouds
734,734,Salalah,OM,17.0151,54.0924,75.29,50,0,4.61,clear sky
735,735,Sechura,PE,-5.5569,-80.8222,77.31,61,98,14.85,overcast clouds
736,736,Arrecife,ES,28.9630,-13.5477,64.38,82,20,8.05,few clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Bluff,NZ,59.70,clear sky,-46.6000,168.3333,
2,Cidreira,BR,69.26,clear sky,-30.1811,-50.2056,
3,Hambantota,LK,77.61,few clouds,6.1241,81.1185,
4,Cabra,ES,55.65,overcast clouds,37.4725,-4.4421,
6,Rikitea,PF,79.18,scattered clouds,-23.1203,-134.9692,
7,Pacific Grove,US,64.58,overcast clouds,36.6177,-121.9166,
8,Westport,US,38.89,overcast clouds,41.1415,-73.3579,
9,Darnah,LY,58.48,overcast clouds,32.7670,22.6367,
10,Mae Sai,TH,73.69,broken clouds,20.4335,99.8762,
11,Hithadhoo,MV,81.55,clear sky,-0.6000,73.0833,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"    

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()  
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [13]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.dropna()
clean_hotel_df = hotel_df.dropna()
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Bluff,NZ,59.70,clear sky,-46.6000,168.3333,Bluff Homestead - Guesthouse & Campervan Park
2,Cidreira,BR,69.26,clear sky,-30.1811,-50.2056,Hotel Castelo
3,Hambantota,LK,77.61,few clouds,6.1241,81.1185,Bungalow 63
4,Cabra,ES,55.65,overcast clouds,37.4725,-4.4421,MS Fuente Las Piedras
6,Rikitea,PF,79.18,scattered clouds,-23.1203,-134.9692,People ThankYou
...,...,...,...,...,...,...,...
732,Kokoda,PG,86.14,broken clouds,-8.8785,147.7407,Daito Guest House
733,San Marcos,US,71.71,few clouds,33.1434,-117.1661,Hampton Inn San Marcos
734,Salalah,OM,75.29,clear sky,17.0151,54.0924,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
735,Sechura,PE,77.31,overcast clouds,-5.5569,-80.8222,Hospedaje Costa Bella
736,Arrecife,ES,64.38,few clouds,28.9630,-13.5477,Hotel Lancelot

In [14]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [19]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [18]:
# 11a. Add a marker layer for each city to the map. 
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.

max_temp = clean_hotel_df["Max Temp"]
current_description = clean_hotel_df["Current Description"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))