## Deliverable 3. Create a Travel Itinerary Map.

In [190]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets
import matplotlib.pyplot as plt
import numpy as np
import os
import csv

# Files to load
weather_py_vacation_csv = os.path.join("../Vacation_Search/WeatherPy_vacation.csv")


# Import the time library and the datetime module from the datetime library 
import time
from datetime import datetime

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [191]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
clean_hotel_df = pd.read_csv(weather_py_vacation_csv)
clean_hotel_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Bluff,NZ,59.70,clear sky,-46.6000,168.3333,Bluff Homestead - Guesthouse & Campervan Park
1,2,Cidreira,BR,69.26,clear sky,-30.1811,-50.2056,Hotel Castelo
2,3,Hambantota,LK,77.61,few clouds,6.1241,81.1185,Bungalow 63
3,4,Cabra,ES,55.65,overcast clouds,37.4725,-4.4421,MS Fuente Las Piedras
4,6,Rikitea,PF,79.18,scattered clouds,-23.1203,-134.9692,People ThankYou
...,...,...,...,...,...,...,...,...
647,732,Kokoda,PG,86.14,broken clouds,-8.8785,147.7407,Daito Guest House
648,733,San Marcos,US,71.71,few clouds,33.1434,-117.1661,Hampton Inn San Marcos
649,734,Salalah,OM,75.29,clear sky,17.0151,54.0924,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
650,735,Sechura,PE,77.31,overcast clouds,-5.5569,-80.8222,Hospedaje Costa Bella
651,736,Arrecife,ES,64.38,few clouds,28.9630,-13.5477,Hotel Lancelot

In [192]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]
locations

         Lat       Lng
0   -46.6000  168.3333
1   -30.1811  -50.2056
2     6.1241   81.1185
3    37.4725   -4.4421
4   -23.1203 -134.9692
..       ...       ...
647  -8.8785  147.7407
648  33.1434 -117.1661
649  17.0151   54.0924
650  -5.5569  -80.8222
651  28.9630  -13.5477

[652 rows x 2 columns]

In [193]:
# 4a. Add a marker layer for each city to the map.
max_temp = clean_hotel_df["Max Temp"]
current_description = clean_hotel_df["Current Description"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [194]:
vacation_df = clean_hotel_df
vacation_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Bluff,NZ,59.70,clear sky,-46.6000,168.3333,Bluff Homestead - Guesthouse & Campervan Park
1,2,Cidreira,BR,69.26,clear sky,-30.1811,-50.2056,Hotel Castelo
2,3,Hambantota,LK,77.61,few clouds,6.1241,81.1185,Bungalow 63
3,4,Cabra,ES,55.65,overcast clouds,37.4725,-4.4421,MS Fuente Las Piedras
4,6,Rikitea,PF,79.18,scattered clouds,-23.1203,-134.9692,People ThankYou
...,...,...,...,...,...,...,...,...
647,732,Kokoda,PG,86.14,broken clouds,-8.8785,147.7407,Daito Guest House
648,733,San Marcos,US,71.71,few clouds,33.1434,-117.1661,Hampton Inn San Marcos
649,734,Salalah,OM,75.29,clear sky,17.0151,54.0924,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
650,735,Sechura,PE,77.31,overcast clouds,-5.5569,-80.8222,Hospedaje Costa Bella
651,736,Arrecife,ES,64.38,few clouds,28.9630,-13.5477,Hotel Lancelot

In [195]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.
#Touros Natal Pitimbu Maceio
vacation_start = vacation_df.loc[(vacation_df["City"])== "Maceio"]
vacation_end = vacation_df.loc[(vacation_df["City"])== "Maceio"]
vacation_stop1 = vacation_df.loc[(vacation_df["City"])== "Pitimbu"]
vacation_stop2 = vacation_df.loc[(vacation_df["City"])== "Natal"]
vacation_stop3 = vacation_df.loc[(vacation_df["City"])== "Touros"]
vacation_start

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
324,380,Maceio,BR,79.81,broken clouds,-9.6658,-35.7353,Hotel Ponta Verde MaceiÃ³

In [196]:
# 6. Get the latitude-longitude pairs"Lat" as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat","Lng"]].to_numpy()
# convert numpy arrays into tuples
start = list(map(tuple, start))

end = vacation_end[["Lat","Lng"]].to_numpy()
end = list(map(tuple, end))

stop1 = vacation_stop1[["Lat","Lng"]].to_numpy()
stop1 = list(map(tuple, stop1))

stop2 = vacation_stop2[["Lat","Lng"]].to_numpy()
stop2 = list(map(tuple, stop2))

stop3 = vacation_stop3[["Lat","Lng"]].to_numpy()
stop3 = list(map(tuple, stop3))

In [203]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
start_end = gmaps.directions_layer(start[0], end[0], waypoints=[stop1[0], stop2[0], stop3[0]], travel_mode ='DRIVING')
fig.add_layer(start_end)
fig

Figure(layout=FigureLayout(height='420px'))

In [204]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,380,Maceio,BR,79.81,broken clouds,-9.6658,-35.7353,Hotel Ponta Verde MaceiÃ³
1,221,Pitimbu,BR,79.39,light rain,-7.4706,-34.8086,Reserva do AbiaÃ­
2,65,Natal,BR,79.32,broken clouds,-5.7950,-35.2094,Villa Park Hotel | Natal
3,41,Touros,BR,80.06,broken clouds,-5.1989,-35.4608,INN NEW HORIZON

In [216]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]
locations

      Lat      Lng
0 -9.6658 -35.7353
1 -7.4706 -34.8086
2 -5.7950 -35.2094
3 -5.1989 -35.4608

In [217]:
# 11a. Add a marker layer for each city to the map.

max_temp = itinerary_df["Max Temp"]
current_description = itinerary_df["Current Description"]
hotel_name = itinerary_df["Hotel Name"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))